name: CI

# Déclencheur : Exécution lors d'un push sur n'importe quelle branche
on: [push]

jobs:
  build-test:
    # Environnement d'exécution
    runs-on: ubuntu-latest

    # Variables d'environnement globales pour le job
    env:
      APP_ENV: testing # Environnement de test

    # Étapes du job
    steps:
      # Étape 1 : Checkout du code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Étape 2 : Configuration de PHP
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          tools: composer # Composer auto
          coverage: none

      # Étape 3 : Installation des dépendances Composer
      - name: Install Composer dependencies
        run: composer install --prefer-dist --no-progress --no-suggest

      # Étape 4 : Affichage d'un message de confirmation
      - name: Display repository info
        run: echo "The ${{ github.repository }} repository has been cloned to the runner."

      # Étape 5 : Exécution des tests unitaires avec PHPUnit
      - name: Run PHPUnit tests
        run: vendor/bin/phpunit